### ISSUE TITLE
pytest option --no-pylint is ignored

### ISSUE THREAD

**Issue by dmig-alarstudios** [carsongee/pytest-pylint#114]
I have a `pytest.ini` with `addopts=--cov=. --no-cov-on-fail --pylint`.

Sometimes when I don't want to run pylint, I add `--no-pylint` option to the `pytest` command. The existence of such option means it should force-disable `pylint` if it was enabled by default. But option `--no-pylint` is just ignored.

Testcase:
```sh
pytest --pylint --no-pylint  # pylint should not run here
```

**Comment by dmig-alarstudios** [comment]
Digging through the code I found out, that `--no-pylint` has no effect now: it was broken by the commit 3790ec0d and fix probably should be added here:
https://github.com/carsongee/pytest-pylint/blob/d56782044868346b1aed922c47ac084a7b521bf3/pytest_pylint/plugin.py#L66-L75

```diff
-    if config.option.pylint:
+    if config.option.pylint and not config.option.no_pylint:
```

**Comment by carsongee** [comment]
Thanks for reporting. It sure isn't there, and there must be a bug with the test for it. I should have it fixed shortly
