### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'do_exit'

### ISSUE THREAD

**Issue by gangefors** [carsongee/pytest-pylint#133]
pylint 2.5.1 changed the lint.Run class definition and rename the parameter `do_exit` to `exit`.
According to https://github.com/PyCQA/pylint/pull/3554 this is a revert of an incorrectly named parameter.

```
INTERNALERROR>   File "/home/stefanga/projects/oe-fwrt/.tox/scripts/lib/python3.5/site-packages/pytest_pylint/plugin.py", line 174, in pytest_collection_finish
INTERNALERROR>     result = lint.Run(args_list, reporter=reporter, do_exit=False)
INTERNALERROR> TypeError: __init__() got an unexpected keyword argument 'do_exit'

```

To get the latest version of pytest-pylint to work one must lock the pylint dependency to <2.5.1.

**Comment by gangefors** [comment]
I would argue that it's pylint that has broken their API which has been stable since 2.0 was released.
https://github.com/PyCQA/pylint/pull/3554

So this issue was just created for others that to find that have the same issue as we had in our CI pipelines.

**Comment by gangefors** [comment]
The issue will be fixed with a deprecation notice in the upcoming 2.5.2 release.
https://github.com/PyCQA/pylint/commit/25223a9e2b84e3f8977ed70f34ee90bb99d4071f

**Comment by carsongee** [comment]
This is now resolved with https://pypi.org/project/pytest-pylint/0.17.0/ that was just released
