### ISSUE TITLE
Invalidate cache if config changed

### ISSUE THREAD

**Issue by michael-k** [carsongee/pytest-pylint#139]
The cache uses the mtime of the files, but doesn't check if config is still the same.  I've stopped disabling a message and pylint passed on my machine.  But it didn't pass in the CI/CD pipeline (no cache).

It took me some time to figure out why it passed on my machine and I guess others might have the same problem.  It would be nice to discard the cache on config changes.

**Comment by michael-k** [comment]
Same problem exists for new releases of pylint(-plugins).  Eg. pylint-django 2.2.0 introduced a “[n]ew checker for hard-coded `auth.User`” ([changelog](https://github.com/PyCQA/pylint-django/blob/v2.2.0/CHANGELOG.rst#version-220-22-jul-2020)).  CI/CD picked that up, but my local setup did not until I deleted the cache.

**Comment by yanqd0** [comment]
It is easy to fix it by your self.

```sh
rm .pytest_cache/v/pylint/mtimes
# or remove all
rm -rf .pytest_cache
# or run without cache
pytest -p no:cacheprovider
```

It is hard to fix it by this plugin. There are too many files to be watched, `pytest.ini`, `setup.cfg`, `tox.ini`, `.pylintrc`, `pylintrc`, `~/.pylintrc`, `pyproject.toml` and so on.

**Comment by michael-k** [comment]
> It is easy to fix it by yourself.

Invalidating the cache is not the problem.  Realizing that it needs to be invalidated is.  I could run it all the time with `-p no:cacheprovider`, but why give up the cache's benefits.

> too many files to be watched

We don't need to watch the files.  pytest-pylint already collects the config.  We could store a hash of the config (or the relevant parts) in the cache.

**Comment by yanqd0** [comment]
Yes, you are right. `pytest-pylint` already know the config, at [pytest_pylint/plugin.py#L110](https://github.com/carsongee/pytest-pylint/blob/master/pytest_pylint/plugin.py#L110).
