### ISSUE TITLE
False positives after adding another fixture

### ISSUE THREAD

**Issue by lhupfeldt** [carsongee/pytest-pylint#142]
Thank you for this excellent plugin.
It initially got rid of all the false positives as promised, but after I added another fixture it now gives false positives again.
I have attached a zip with an example.
The error is related to import of application code. Removing an import makes the false positive go away, see the comments in the file `test/false_positive_for_fixture_test.py`
[pylint_pytest_bug.zip](https://github.com/carsongee/pytest-pylint/files/5323258/pylint_pytest_bug.zip)
.

**Comment by carsongee** [comment]
I'm not sure I understand the issue. Is this with pylint or pytest-pylint? It seems more related to pylint itself. Could you perhaps create a minimal example without using a zip file? Thanks!
