### ISSUE TITLE
doesn't work if using "enable" in pylintrc

### ISSUE THREAD

**Issue by codydjango** [carsongee/pytest-pylint#159]
Can I get a confirmation that this doesn't work if we're using the "enable" config value in the pylintrc?

For example: 

```
[MASTER]
persistent=yes
load-plugins=pylint_pytest
jobs=1

[MESSAGES CONTROL]
disable=all
enable=W0621
```

With said config, if linting a test file using pylint fixtures, I see the "redefined-outer-name" lint message.

Seems like any rules that are "enabled" take precedencece over the plugin?

**Comment by codydjango** [comment]
If this is actually the case, it really restricts the use of this plugin. It's fairly common to disable all, and then only enable specific rules,  especially when working with older codebases.

**Comment by carsongee** [comment]
It seems to work as I would expect. Using this as the file:
```python
foo = 'hi'

def foo():
    foo = 'boo'
```
and running `pytest --pylint` with no pylintrc, I get:
```
pytest --pylint
================================================= test session starts ==================================================
platform linux -- Python 3.8.1, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/x/tmp/pylintt
plugins: pylint-0.18.0
collected 1 item
--------------------------------------------------------------------------------
Linting files
.
--------------------------------------------------------------------------------

test.py F                                                                                                        [100%]

======================================================= FAILURES =======================================================
___________________________________________________ [pylint] test.py ___________________________________________________
C:  1, 0: Missing module docstring (missing-module-docstring)
C:  1, 0: Black listed name "foo" (blacklisted-name)
E:  3, 0: function already defined line 1 (function-redefined)
C:  3, 0: Black listed name "foo" (blacklisted-name)
C:  3, 0: Missing function or method docstring (missing-function-docstring)
W:  4, 4: Redefining name 'foo' from outer scope (line 1) (redefined-outer-name)
C:  4, 4: Black listed name "foo" (blacklisted-name)
W:  4, 4: Unused variable 'foo' (unused-variable)
=============================================== short test summary info ================================================
FAILED test.py::PYLINT
```

and with your pylintrc I get:
```
================================================= test session starts ==================================================
platform linux -- Python 3.8.1, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: /home/x/tmp/pylintt
plugins: pylint-0.18.0
collected 1 item
--------------------------------------------------------------------------------
Linting files
.
--------------------------------------------------------------------------------

test.py F                                                                                                        [100%]

======================================================= FAILURES =======================================================
___________________________________________________ [pylint] test.py ___________________________________________________
W:  4, 4: Redefining name 'foo' from outer scope (line 1) (redefined-outer-name)
=============================================== short test summary info ================================================
FAILED test.py::PYLINT
================================================== 1 failed in 0.23s ===================================================
```
Where `redefined-outer-name` is the one message you have enabled  as W0621

**Comment by carsongee** [comment]
I would also add, that it is the same behavior of just running vanilla `pylint test.py`, so if there is still an issue you are having, I'd suggest reporting it on the [pylint project](https://github.com/PyCQA/pylint) project directly

**Comment by codydjango** [comment]
I think there's been a miscommunication here -- in my original post I wrote "with said config, if linting a test file *using pylint fixtures*, I see the "redefined-outer-name" lint message."

In your example file you aren't using pytest fixtures. So yes, you're correct that with your file you are seeing the desired pylint behaviour. 

In my usecase, using the following as the file:

```
import pytest

@pytest.fixture
def foo():
    return 'boo'

def test_foo(foo):
    assert foo == 'boo'
```

I'd expect that the "redefined-outer-name" rule would be suppressed since I'm using pylint fixtures. But instead, it's still present in the output (when using my pylintrc config, shown above). If I remove the 'redefined-outer-name' rule from the "enable" configuration, I can see that the pytest-pylint plugin works as expected again, suppressing the warning. 


Makes sense?
