### ISSUE TITLE
File contains no section headers

### ISSUE THREAD

**Issue by AndreMPCosta** [carsongee/pytest-pylint#165]
If I run pylint alone, it works fine.
When I run pytest --pylint, I get:

```
INTERNALERROR> configparser.MissingSectionHeaderError: File contains no section headers.
INTERNALERROR> file: 'G:\\risk-util-tool\\engine\\.pylintrc', line: 1
INTERNALERROR> 'ï»¿[MASTER]\n'
```
So probably a encoding issue.

I've generated my config like this:
```
pylint --generate-rcfile | out-file -encoding utf8 .pylintrc  
```

**Comment by carsongee** [comment]
Can you try this again with the latest version (0.19.0)? I believe this should be resolved as we've changed this area of the code quite a bit, but I might be wrong
