### ISSUE TITLE
`PytestRemovedIn8Warning` in `plugin.py:311`

### ISSUE THREAD

**Issue by gaborschulz** [carsongee/pytest-pylint#177]
Pytest shows a warning that py.path.local is deprecated:

`.../pytest_pylint/plugin.py:311: PytestRemovedIn8Warning: The (fspath: py.path.local) argument to PylintFile is deprecated. Please use the (path: pathlib.Path) argument instead.`

https://docs.pytest.org/en/latest/deprecations.html#fspath-argument-for-node-constructors-replaced-with-pathlib-path

**Comment by dolfandringa** [comment]
For reference, this is the disaster I am trying (and failing) to stay backwards compatible with pytest 5.4. https://github.com/carsongee/pytest-pylint/compare/main...dolfandringa:pytest-pylint:feature/pytest7_compliance?expand=1

**Comment by carsongee** [comment]
Yeah, I gave up to. I put out a 0.20.0 a few minutes ago as the last release to support pytest <7. I'll release 0.21.0 shortly to drop this and support the main branch of pytest/pytest 8.0 when it comes out
