### ISSUE TITLE
ProgrammaticReporter is using  __implements__ iheritance pattern for BaseReporter which is deprecated in pylint version 5.12.0 (or earlier) 

### ISSUE THREAD

**Issue by zenndos** [carsongee/pytest-pylint#179]
file: `pytest_pylint/pylint_util.py`

class `ProgrammaticReporter`

resulting error/warning:

> DeprecationWarning: Using the __implements__ inheritance pattern for BaseReporter is no longer supported. Child classes should only inherit BaseReporter

I saw that the error was already fixed in the code, but the release for it is missing.

**Comment by carsongee** [comment]
It is now released
