### ISSUE TITLE
Support ignoring warnings on a per-file basis

### ISSUE THREAD

**Issue by abendebury** [carsongee/pytest-pylint#18]
In pytest-flake8, you can ignore errors on a per-file basis, for example:

```
[pytest]
flake8-ignore = populate_db.py ALL
    config.py E501  ; Long lines happen in the config file
```

This would be nice to support in pytest-pylint as well, as currently the only equivalent is ignoring all errors in a certain file, which is not always desirable.

**Comment by carsongee** [comment]
I feel this is better done using the existing pylint controls for this type of message control with either adding full project disables for that error or adding `# pylint: disable=unused-variables` type comment controls to specific files.  For example it can change max line length with:
```ini
[FORMAT]

# Maximum number of characters on a single line.
max-line-length=12
```
Or ignore a file with something like:
```ini
[MASTER]

ignore = migrations,docs/conf.py
```

that said, being able to control messages for a given file from the configuration seems like a good potential feature for pylint.

**Comment by PlasmaSheep** [comment]
Comment controls are not great because they add source file noise, which I (and a lot of other people) find objectionable.

Your ini examples are too coarse in my opinion, since the first does not act on a per-file basis and the second does not discriminate based on errors. So I think this feature would be filling a niche that needs filling.

**Comment by carsongee** [comment]
I can't disagree with you on the first point, but I think the ideal place to fix this would be in [pylint](https://github.com/PyCQA/pylint) directly so you can take advantage of it regardless of the test runner.  That said, I'd accept code to add it to this plugin as well, I just don't see having the time to write it myself.
