### ISSUE TITLE
pytest-pylint is not available in conda-forge

### ISSUE THREAD

**Issue by holgern** [carsongee/pytest-pylint#36]
Hello,
I need your package as a dependency to be available in conda-forge.
I created https://github.com/conda-forge/staged-recipes/pull/5106 and added your package.

My question is now, do you want to be added as conda-forge maintainer for the pytest-pylint package?
This means that you have write rights for the pytest-pylint-feedstock package and could push new releases to cona-forge.

Best regards
Holger

**Comment by carsongee** [comment]
I haven't used conda in a few years, and I haven't ever made a recipe, so I don't feel very qualified to be the maintainer, but I'm always happy to help in any way I can, and if that means learning how to maintain the recipe, I can learn, but otherwise, I'd be happy to defer to you!

**Comment by holgern** [comment]
The feedstock is ready now:
https://github.com/conda-forge/pytest-pylint-feedstock
but needs some time for building.

**Comment by holgern** [comment]
I tested the conda-build for windows and it worked. 
You can add some more nice badges from conda:
`
.. image:: https://anaconda.org/conda-forge/pytest-pylint/badges/version.svg   
    :target: https://anaconda.org/conda-forge/pytest-pylint
  
.. image:: https://anaconda.org/conda-forge/pytest-pylint/badges/downloads.svg   
    :target: https://anaconda.org/conda-forge/pytest-pylint

`

**Comment by carsongee** [comment]
Woohoo, all the badges!
