### ISSUE TITLE
pylint check only unsed imports

### ISSUE THREAD

**Issue by Formartha** [carsongee/pytest-pylint#43]
Hi,

I would like to check only unsed imports & compiling issues - can it be done somehow? (i don't mind for now about line size, dots, etc).

**Comment by carsongee** [comment]
You can manage this through pylintrc: https://docs.pylint.org/en/1.6.0/run.html. Additionally, I have a flag to only check for the more critical errors like `Errors` and `Failures`, or maybe just `Failures` is all you want. You can add `--pylint-error-types=EF` to your invocation of pytest for errors and failures or `--pylint-error-types=F` for just failures.
