### ISSUE TITLE
Support disabling pylint via the command line

### ISSUE THREAD

**Issue by orf** [carsongee/pytest-pylint#48]
Hey, thank you for this package! I have a small feature request - we add `--pylint` to our `setup.cfg` file so that it is always run alongside our tests:

```
[tool:pytest]
addopts = -p no:cacheprovider -n auto --junitxml /tmp/unit_results.xml --pylint
```

This works fine, but I find myself wishing to just run our tests locally without the linting (which is a bit faster). 

I'd love the ability to run `pytest --no-pylint` and have it override the auto-included `--pylint` flag, so that `pytest --pylint --no-pylint` will not run pylint.

**Comment by carsongee** [comment]
This is a great idea, I've often found myself wanting the same thing.

**Comment by orf** [comment]
Awesome, thank you for the fast turnaround!
