### ISSUE TITLE
print something while pylint is running so CI services know it's still running

### ISSUE THREAD

**Issue by jwkvam** [carsongee/pytest-pylint#52]
# Issue

CircleCI and probably other services timeout the test if no output is received. It would be helpful to print something while pylint is running to indicate the test hasn't stalled.

# One Idea

Print something during `handle_message`, for example:
```
    def handle_message(self, msg):
        """Get message and append to our data structure"""
        self.data.append(msg)
        print('.', end='')
        sys.stdout.flush()
```
And add another argument to enable this behavior. Downside is it just creates a lot of `.`. Don't know if there's something quick and more clever.

I'm happy to create a PR with this if you like.

Edit: A better option would probably be to override `on_set_current_module`
https://github.com/PyCQA/pylint/blob/3a8635a9ef85759f96bfefd8edcd70e223fd12bb/pylint/reporters/__init__.py#L96
so we only have one dot per file.

**Comment by jwkvam** [comment]
Eh, this isn't as important as I thought. I had pylint set to 0 jobs which seems to cause issues with CircleCI. Changing it to 1 stops pylint from hanging :/ sorry for the noise. Feel free to close if you want.

**Comment by carsongee** [comment]
This seems like a good change to me.  Specifically doing one per file.  If you'd like to submit a PR to do it, great! If not, I'll plan on working on it (probably this weekend or next).
