### ISSUE TITLE
Ignore paths not working

### ISSUE THREAD

**Issue by khokhlin** [carsongee/pytest-pylint#81]
Hi!

If I use full path (ignore=models/migrations/) in ignore option in my .pylintrc it doesn't work.

**Comment by carsongee** [comment]
Can you give me a few more details about your folder structure so I can reproduce locally? Thanks!

**Comment by khokhlin** [comment]
```
./.pylintrc
./foo
./foo/__init__.py
./bar
./bar/__init__.py
./bar/foo
./bar/foo/__init__.py
```
I'm looking for a way to ignore the **foo** but not the **bar/foo**.
