### ISSUE TITLE
How to run pylint-pytest as a pytest from code?

### ISSUE THREAD

**Issue by dickreuter** [carsongee/pytest-pylint#84]
How can I run pylint-pytest from a test (rather than from command line) for c:\git\example\*.py?

**Comment by carsongee** [comment]
The simplest way I can think of doing that is just to make an external call from within the test. I.e.
```python
import subprocess
subprocess.run(['pytest', '--pylint', 'c:\git\example*.py'])
```
 That said, this project is just a plug-in to pytest, so if they have a more elegant way to invoke programmatically this plug-in should work with that method. So, you might ask on their project for help there. Thanks!
