### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by sp-daniel-pinyol** [carsongee/pytest-pylint#90]
On my project executing just "pytest" I get ModuleNotFoundError, but with "python -m pytest" it works. It's related to https://medium.com/@dirk.avery/pytest-modulenotfounderror-no-module-named-requests-a770e6926ac5 , but none of the suggestions there work.

With "py.test --pylint" I also get ModuleNotFoundError. Any suggestion?

thanks

**Comment by stevenhair** [comment]
I ran into the same problem. For what it's worth, pylint will run just fine from bash but not from zsh. Whatever this issue is, it's specific to pylint and not pytest-pylint.
