### ISSUE TITLE
typed-ast version issue with python 3.6 on linux

### ISSUE THREAD

**Issue by gouarin** [carsongee/pytest-pylint#92]
I have an error since the new release of pytest-pylint on conda-forge.

I test my project with various python version on Linux and MacOS and I have an issue only with Python 3.6 on Linux. It works on MacOS with the same version of pylint (2.3.1), pytest (4.3.0), typed-ast (1.3.1) and pytest-pylint (0.14.0).

The error message is

```
pluggy.manager.PluginValidationError: Plugin 'pylint' could not be loaded: (typed-ast 1.3.1 (/home/travis/miniconda/envs/pylbm_env/lib/python3.6/site-packages), Requirement.parse('typed-ast<1.3.0; python_version < "3.7" and implementation_name == "cpython"'), {'astroid'})!
```

If you want to see the logs for both:

- On Linux: https://travis-ci.org/pylbm/pylbm/jobs/502661193
- On MacOS: https://travis-ci.org/pylbm/pylbm/jobs/502661196

Tell me if it's not related to `pytest-pylint`

**Comment by carsongee** [comment]
It doesn't appear to be a failure of pytest-pylint because it is happening before pytest is getting invoked, which in turn invokes this plugin.  It appears to be somewhere between astroid, ast, and pylint, so I'd ask around there.  Thanks for reporting!
