### ISSUE TITLE
How can I ignore test files with `setup.cfg`?

### ISSUE THREAD

**Issue by MartinThoma** [carsongee/pytest-pylint#94]
I currently have all my configuration in a `setup.cfg`. Adding this seems not to have an effect:

```
[pylint]
disable = W1202
ignore-patterns=test_.*?py
```

Does it work differently?

**Comment by carsongee** [comment]
Currently, pytest-pylint only auto attempts to find your configuration at `pylintrc`. You can try specifying `setup.cfg` with the switch `--pylint-rcfile=setup.cfg` with your `pytest` invocation, but I don't think I've tested it with `setup.cfg` so ymmv.
