### ISSUE TITLE
Support --pylint-ignore and --pylint-ignore-patterns flags

### ISSUE THREAD

**Issue by fredthomsen** [carsongee/pytest-pylint#95]
Pass through these options to pylint equivalents.  I have seen the option for patterns now working in .pylintrc via issue #81.  When running tox for multiple environments, I had a use case where for a py2.7 run I wanted to ignore a certain file.  Happy to raise a PR for this if it is desired/fits the goals of the project.

**Comment by carsongee** [comment]
I think my preferred mechanism for this would be to have you specify different pylintrc files in tox for your different python versions.  That way there aren't two ways to handle ignore, which seems more pythonic.  It would also reduce bug opportunities in this plugin.  If you feel strongly about it-or that won't work for your case-I'd still consider a PR for the proposed change.

**Comment by fredthomsen** [comment]
Understood.  Having two pylintrc files for a one line difference seems
strange to me, so I'll throw something together and let you approve or veto
it.

**Comment by carsongee** [comment]
Closed by https://github.com/carsongee/pytest-pylint/pull/107
